# Generated by Django 5.0.12 on 2025-02-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Da',
            fields=[
                ('ma_da', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_da', models.CharField(max_length=50)),
                ('mau_sac', models.CharField(max_length=30)),
                ('carat', models.FloatField()),
                ('gia_ban', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DonBan',
            fields=[
                ('ma_db', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_ban', models.DateField()),
                ('tong_tien', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('ma_km', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loai', models.CharField(max_length=100)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('chiet_khau', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dang_nhap', models.CharField(max_length=50, unique=True)),
                ('mat_khau', models.CharField(max_length=100)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nữ')], default='Nam', max_length=3)),
                ('sdt', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quay',
            fields=[
                ('ma_quay', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('so_quay', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UuDai',
            fields=[
                ('ma_uu_dai', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loai', models.CharField(max_length=100)),
                ('diem_tich_luy', models.FloatField()),
                ('chiet_khau', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nv', models.CharField(max_length=20)),
                ('chuc_vu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vang',
            fields=[
                ('ma_vang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loai_vang', models.CharField(max_length=50)),
                ('gia_mua', models.FloatField()),
                ('gia_ban', models.FloatField()),
                ('ngay_cap_nhat', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.da')),
            ],
        ),
        migrations.CreateModel(
            name='ChinhSachBaoHanh',
            fields=[
                ('ma_bh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mo_ta', models.TextField()),
                ('thoi_gian_bao_hanh', models.PositiveIntegerField()),
                ('don_ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.donban')),
            ],
        ),
        migrations.CreateModel(
            name='HoSoKhachHang',
            fields=[
                ('ma_khach', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nữ')], default='Nam', max_length=3)),
                ('diem_tich_luy', models.IntegerField()),
                ('sdt', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dia_chi', models.CharField(max_length=200)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.nguoidung')),
                ('vai_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vaitro')),
            ],
        ),
        migrations.CreateModel(
            name='DonMua',
            fields=[
                ('ma_dm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_mua', models.DateField()),
                ('tong_don_mua', models.FloatField()),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien')),
            ],
        ),
        migrations.AddField(
            model_name='donban',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien'),
        ),
        migrations.CreateModel(
            name='DoanhThuNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('doanh_thu', models.FloatField()),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='DoanhThuQuay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('doanh_thu', models.FloatField()),
                ('quay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quay')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_sp', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_sp', models.CharField(max_length=100)),
                ('trong_luong', models.FloatField()),
                ('gia_ban', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mo_ta', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('da', models.ManyToManyField(through='main.ChiTietDa', to='main.da')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don', models.CharField(max_length=20)),
                ('so_luong', models.PositiveIntegerField()),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sanpham')),
            ],
        ),
        migrations.AddField(
            model_name='chitietda',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sanpham'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.nguoidung')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuGiaVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('gia_mua', models.FloatField()),
                ('gia_ban', models.FloatField()),
                ('vang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vang')),
            ],
            options={
                'unique_together': {('vang', 'ngay')},
            },
        ),
    ]
