# Generated by Django 5.0.12 on 2025-02-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price_14k', models.DecimalField(decimal_places=0, max_digits=12)),
                ('price_18k', models.DecimalField(decimal_places=0, max_digits=12)),
                ('price_24k', models.DecimalField(decimal_places=0, max_digits=12)),
                ('price_9999', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('NHAN', 'Nhẫn'), ('DAYCHUYEN', 'Dây chuyền'), ('VONGTAY', 'Vòng tay'), ('BONGTAI', 'Bông tai')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gold_type', models.CharField(choices=[('14K', '14 Karat'), ('18K', '18 Karat'), ('24K', '24 Karat'), ('9999', '9999 Pure Gold')], max_length=5)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('contact_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
