# Generated by Django 4.2.19 on 2025-02-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CustomerReview',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
