# Generated by Django 5.0.12 on 2025-02-16 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinhSachBaoHanh',
            fields=[
                ('ma_bh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mo_ta', models.TextField()),
                ('thoi_gian_bao_hanh', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don', models.CharField(max_length=20)),
                ('so_luong', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Da',
            fields=[
                ('ma_da', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_da', models.CharField(max_length=50)),
                ('mau_sac', models.CharField(max_length=30)),
                ('carat', models.FloatField()),
                ('gia_ban', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DoanhThuNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('doanh_thu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DoanhThuQuay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('doanh_thu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DonBan',
            fields=[
                ('ma_db', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_ban', models.DateField()),
                ('tong_tien', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DonMua',
            fields=[
                ('ma_dm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_mua', models.DateField()),
                ('tong_don_mua', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HoSoKhachHang',
            fields=[
                ('ma_khach', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.BooleanField()),
                ('diem_tich_luy', models.IntegerField()),
                ('sdt', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dia_chi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('ma_km', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loai', models.CharField(max_length=100)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('chiet_khau', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LichSuGiaVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('gia_mua', models.FloatField()),
                ('gia_ban', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dang_nhap', models.CharField(max_length=50, unique=True)),
                ('mat_khau', models.CharField(max_length=100)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.BooleanField()),
                ('sdt', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='Quay',
            fields=[
                ('ma_quay', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('so_quay', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_sp', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_sp', models.CharField(max_length=100)),
                ('trong_luong', models.FloatField()),
                ('gia_ban', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UuDai',
            fields=[
                ('ma_uu_dai', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loai', models.CharField(max_length=100)),
                ('diem_tich_luy', models.FloatField()),
                ('chiet_khau', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nv', models.CharField(max_length=20)),
                ('chuc_vu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vang',
            fields=[
                ('ma_vang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loai_vang', models.CharField(max_length=50)),
                ('gia_mua', models.FloatField()),
                ('gia_ban', models.FloatField()),
                ('ngay_cap_nhat', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GoldPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gold_type',
        ),
        migrations.AddField(
            model_name='chitietda',
            name='da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.da'),
        ),
        migrations.AddField(
            model_name='chinhsachbaohanh',
            name='don_ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.donban'),
        ),
        migrations.AddField(
            model_name='hosokhachhang',
            name='nguoi_dung',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.nguoidung'),
        ),
        migrations.AddField(
            model_name='donmua',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien'),
        ),
        migrations.AddField(
            model_name='donban',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien'),
        ),
        migrations.AddField(
            model_name='doanhthunhanvien',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien'),
        ),
        migrations.AddField(
            model_name='doanhthuquay',
            name='quay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quay'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='da',
            field=models.ManyToManyField(through='main.ChiTietDa', to='main.da'),
        ),
        migrations.AddField(
            model_name='chitietdon',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sanpham'),
        ),
        migrations.AddField(
            model_name='chitietda',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sanpham'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='vai_tro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vaitro'),
        ),
        migrations.AddField(
            model_name='lichsugiavang',
            name='vang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vang'),
        ),
        migrations.AlterUniqueTogether(
            name='lichsugiavang',
            unique_together={('vang', 'ngay')},
        ),
    ]
